### ISSUE TITLE
Centig should throw, when user tries to get non-existing configuration

### ISSUE THREAD

**Issue by halfzebra** [Alexloof/centig#5]
When the configuration key is removed from the schema, but code still depends on it, there's an opportunity for receiving a non-existent key.

I propose to throw an error if configuration does not contain the requested key.

How does that sound?

**Comment by Alexloof** [comment]
Yes, i got your point. I will fix it in next release :)

**Comment by Alexloof** [comment]
Released in [](https://github.com/Alexloof/centig/releases/tag/v1.0.14)

**Comment by halfzebra** [comment]
Thanks for a very nice addition! :+1:
