### ISSUE TITLE
Using 'type' doesn't reflect preprocessed value

### ISSUE THREAD

**Issue by Silind** [Alexloof/centig#6]
When the `preprocess` function is given along with a `type`, the type should reflect the return type of the preprocessed value rather than the initial value.

**Example code**
```javascript
port: {
  type: Number,
  env: 'PORT',
  preprocess: value => Number(value),
  validate: validatePort,
}
```

**Actual behavior**
Since the env-variable is a `String` type, an error is thrown:
*3000 is not of type Number.*

**Expected behavior**
No error should be thrown since the return type of the function handed to `preprocess` matches the `type` given.

**Comment by Alexloof** [comment]
@Silind Good catch, ill try to find time to fix it. Feel free to send a PR if you need the fix asap 👍

**Comment by Silind** [comment]
My apologies, the problem had its origin somewhere else.
It does already work is expected 😅 

I'll close this issue again.
