### ISSUE TITLE
Feature request: Undefined values should result in an error.

### ISSUE THREAD

**Issue by Silind** [Alexloof/centig#7]
Similar to [#5](https://github.com/Alexloof/centig/issues/5)
If I create a centig config like this:
```javascript
const config = centig({
  db: {
    host: 'localhost',
    port: 5050,
    name: 'admin',
  },
});
```

And accidentally try to access a value like:
```javascript
const host = config.get('host'); // undefined
``` 
the value of `host` will be `undefined`.
  
**Requested behavior**
This should result in an error being thrown and the application to crash (unless explicitly caught).

**Comment by Alexloof** [comment]
Released in [v1.0.14](https://github.com/Alexloof/centig/releases/tag/v1.0.14)
